### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/tabs-to-spaces#18]
I am getting this error on installs.  After the recent problems I suspect npm.  In any case this is what I'm seeing.

    Installing tabs-to-spaces@0.8.1 to C:\Users\Administrator\.atom\packages
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: ENOENT, open 'C:\Users\Administrator\.atom\packages\tabs-to-spaces\.npmignore'

**Comment by mark-hahn** [comment]
windows 8.1
atom 176
apm  0.128.0
npm  2.3.0
node 0.10.35
python 2.7.8
git 1.7.11.msysgit.1
visual studio 2013

**Comment by lee-dohm** [comment]
Interesting. I'm looking at the code changes between v0.8.0&rarr;v0.8.1 and I don't see anything that should cause this. I'll look into it more this afternoon.

**Comment by mark-hahn** [comment]
I just did an install and it worked fine.  I wish you could upgrade
individual packages from the command line.

**Comment by lee-dohm** [comment]
You can: `apm upgrade package-name`

**Comment by mark-hahn** [comment]
I tried that and got all of them as if the package name wasn't there.  I'll
try again.

**Comment by lee-dohm** [comment]
Were you able to get updated?

**Comment by lee-dohm** [comment]
I doubt this is still an issue. If you run into it again, let me know :grinning:
