### ISSUE TITLE
strange message during apm upgrade

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/tabs-to-spaces#28]
```
Installing tabs-to-spaces@0.10.0 to /root/.atom/packages 
Note: The code generator has deoptimised the styling of 
"/root/.atom/packages/tabs-to-spaces/sample/jquery-git2.js" 
as it exceeds the max of "100KB".
```

**Comment by lee-dohm** [comment]
Hmmmm ... that is interesting. I include that file in the repository for testing #16. It isn't part of the package really. I'll have to take a look at how I could prevent it from being included in the install package.
