### ISSUE TITLE
Converting spaces to tabs leaves spaces

### ISSUE THREAD

**Issue by bobrocke** [lee-dohm/tabs-to-spaces#30]
If I have a file with indents of 4 spaces that I open with the language set to an indention of 3 and then convert spaces to tabs, I get a tab and a space where there were 4 spaces and two tabs and then two spaces where there were 8 spaces,

I'd rather have those four spaces converted to tabs of 3 spaces.

Would that have been the expectation?

**Comment by lee-dohm** [comment]
How do I know those 4 spaces were intended to be one tab of 4 spaces and not two tabs of 2 spaces? Or one tab of three spaces and a space? Or 4 one-space tabs? I could do some numeric analysis, but there is still no way to be certain.

Also, there is visual alignment to worry about. What if some things are designed to be aligned visually and I go changing things? The package has no way (at least no easy way) of determining intent in this case.

So the package errs on the side of keeping things as they are as much as possible.

What you can do is change your settings to 4-space tabs, tabify the document, and then return your settings to 3-space tabs.
