### ISSUE TITLE
Quesion about tabify

### ISSUE THREAD

**Issue by ArtskydJ** [lee-dohm/tabs-to-spaces#31]
Can this untabify non-leading whitespace and tabify leading whitespace in one command?

In one command/keyboard shortcut, could I turn this
```js
····x————··y
```
into this?
```js
————x······y
```

Basically `untabify-all` followed by `tabify`?
Is this the current behavior of `tabify`?

**Comment by lee-dohm** [comment]
The tabify command only works on leading whitespace, leaving whatever you have after the first non-whitespace character alone. If you wanted to make the conversion that you have pictured (and you have tabs set to be equivalent to four spaces), yes, you could execute untabify-all followed by tabify to achieve what you want.

If you want to have a single command and keybinding that does both, you can use this technique from the Atom documentation to do so:

https://atom.io/docs/latest/behind-atom-keymaps-in-depth#composed-commands

**Comment by ArtskydJ** [comment]
Thanks!
