### ISSUE TITLE
Package does not listen to config.cson

### ISSUE THREAD

**Issue by devotox** [lee-dohm/tabs-to-spaces#32]
In my config.cson i have
*
  tabs-to-spaces: tabify
.config
  tabs-to-spaces: untabify

the untabify never works ive tried *.config, .config and just put the file directly as settings.config and none will take effect

**Comment by lee-dohm** [comment]
Can you put what you have in your `config.cson` in a [fenced code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)? The quotes and indentation are important.

**Comment by lee-dohm** [comment]
You can also always use the Settings View to configure the package rather than editing the `config.cson` directly.

**Comment by devotox** [comment]
In the settings view i cannot change the behavior per file type though. 

The reason i need this is i generally want everything tabbed but yaml files as yaml chokes when tabs are used as indentation rather than spaces

```cson
"*":
  "exception-reporting":
    userId: "526931d5-be32-7331-1961-8d5fbfcd9efa"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
    showInvisibles: true
    tabLength: 4
    softWrap: true
  "tabs-to-spaces":
    onSave: "tabify"
".config":
  "tabs-to-spaces":
    onSave: "untabify"
```

**Comment by lee-dohm** [comment]
Then what you want is:

```
".source.yaml":
  "tabs-to-spaces":
    onSave: "untabify"
```

**Comment by devotox** [comment]
No because all the files are .config files not .yaml as they are used in AWS and thats the file extension Amazon wants

but do i put .source.config?

**Comment by lee-dohm** [comment]
The language-specific config doesn't key off of the file extension. It keys off of the "scope descriptor", which for YAML files is `.source.yaml`, no matter what file extension is used to store the YAML.

**Comment by devotox** [comment]
Ha thank you that makes more sense now

**Comment by devotox** [comment]
It works perfectly

**Comment by devotox** [comment]
thank you. 
ps. I probably should have also put all 3 of this messages together

**Comment by lee-dohm** [comment]
Great! Glad I could help out :grinning:
