### ISSUE TITLE
For JavaScript, take eslint indent config into account

### ISSUE THREAD

**Issue by brettz9** [lee-dohm/tabs-to-spaces#36]
Hi!

It would be great if tabs-to-spaces could take into account a file/project's configuration from ESLint to determine how to do replacements: http://eslint.org/docs/rules/indent

**Comment by lee-dohm** [comment]
I assume you're talking about the on save functionality of tabs-to-spaces? There are a few issues or edge cases I see:

* Would duplicate a lot of code from ESLint (and hence need to be kept up-to-date with some version, possibly multiple versions, of ESLint)
* Would only be useful for JavaScript
* Detection of minified JavaScript (I assume that minified JavaScript would not be modified)
* tabs-to-spaces is specifically designed to maintain visual alignment of code, this feature would break that contract
* Is behaving differently on manual execution and on-save reasonable? Will this break other user's expectations? (Whenever that is a question, the answer is almost always "probably".)

Given that, according to the documentation you link, ESLint can fix this for you, I think the most prudent thing would be to simply call ESLint and have it work the magic. And if that is the case, a separate package is probably best.
