### ISSUE TITLE
not doing anything for me

### ISSUE THREAD

**Issue by rralian** [lee-dohm/tabs-to-spaces#47]
I've installed the tabs-to-spaces package and enabled it in Atom 1.9.7. I've loaded a javascript file that mixes spaces and tabs at the beginning of lines. When I run `tabify` it doesn't appear to do anything. Neither does `untabify` or `untabify all`.

I would expect this to just operate on the open file (the docs aren't clear about this), but I've also tried highlighting bits of code, and it doesn't seem to make any changes there either. Do you know if there are compatibility issues with nuclide or esformatter?

**Comment by lee-dohm** [comment]
It shouldn't make any visible changes at all if you don't have Show Invisibles enabled. Everything should maintain the same visual alignment but the underlying characters change from spaces to tabs or vice versa.

So far, it sounds like things are working as expected. Can you give a little more information? Perhaps some steps to reproduce the problem? What do you expect to happen? What is actually happening?

**Comment by lee-dohm** [comment]
Please let me know if you have any more questions. If there is something going wrong, I'd like to fix it. If you can give me some more details, I'll reopen the issue.
