### ISSUE TITLE
File type specific configuration possible?

### ISSUE THREAD

**Issue by yashmankad** [lee-dohm/tabs-to-spaces#48]
I'm new to Atom and came across this extremely useful package. Like the example mentioned about having different onSave settings for different languages - can I do something similar for Makefiles?

I have tried the following in my ```config.cson``` but it doesn't work-

```
"*"
 "tabs-to-spaces":
   onSave: "untabify"
"Makefile":
  "tabs-to-spaces":
    onSave: "tabify"
```

**Comment by lee-dohm** [comment]
You can find information on how to add language-specific configuration directly to your `config.cson` in the [Atom Flight Manual](http://flight-manual.atom.io):

http://flight-manual.atom.io/using-atom/sections/basic-customization/#language-specific-settings-in-your-config-file

What you're missing is the scope name for a Makefile. I don't know what language package you have installed for Makefile support, so I can't tell you what scope you would need. But the Flight Manual shows you how to do it.
