### ISSUE TITLE
No note in documentation how to install and use this plugin

### ISSUE THREAD

**Issue by john-dgi-vof-com** [lee-dohm/tabs-to-spaces#56]
No note in documentation how to install and use this plugin

**Comment by lee-dohm** [comment]
Instructions on [how to install Atom packages](http://flight-manual.atom.io/using-atom/sections/atom-packages/) and [how to execute commands](http://flight-manual.atom.io/getting-started/sections/atom-basics/#command-palette) are in the [Atom Flight Manual](http://flight-manual.atom.io). I don't believe that it is necessary to duplicate that information here. I would be open to reviewing a pull request that added links to the appropriate sections of the Flight Manual though.
