### ISSUE TITLE
no tabs converted to spaces in v1.23.1 on Sierra 10.12.6

### ISSUE THREAD

**Issue by srperetz** [lee-dohm/tabs-to-spaces#57]
I have a javascript file open that has hard tabs.  When I select Convert Tabs to Spaces or Convert All Tabs to Spaces, nothing happens.  Still all hard tabs.

**Comment by lee-dohm** [comment]
This package does not contain commands named "Convert Tabs to Spaces" or "Convert All Tabs to Spaces". I assume that you're talking about the built-in Atom commands. If I am correct, then you should file an issue on the [whitespace package](https://github.com/atom/whitespace) which is the built-in Atom package that provides those commands.

**Comment by srperetz** [comment]
Oops, sorry, I thought this was the right package, my bad.
