### ISSUE TITLE
Cannot save files after update

### ISSUE THREAD

**Issue by archielee** [lee-dohm/tabs-to-spaces#60]
Hi, after updating to v1.0.4 I can no longer save .cpp, .h, or .hpp files in Atom. I tried in safe mode and I could save there. I could also save .txt files. After disabling the plugin, all my files were saving without issue.

```
Atom 1.23.3 x64
Ubuntu 16.04
tabs-to-spaces 1.0.4
```

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/lee-dohm/tabs-to-spaces/issues/59. Please update to the latest version of Atom.

**Comment by archielee** [comment]
Thanks
